import exceptions

findUser = "{\"_id\": 0, \"userId\": 1}"

getUserCreds = "{\"_id\": 0, \"userId\": 1, \"password\": 1, \"pin_code\": 1}"

# result = db.objects.insert_one(

#     {"last_modified": datetime.datetime.now()})


# addNewUser = ({ userId: "userId", password: "passwd", pin_code: "pin", size: { h: 28, w: 35.5, uom: "cm" } })